"""Autogenerated

Revision ID: 17fb61fdf03c
Revises: e93ead9de071
Create Date: 2023-03-29 18:56:28.733731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17fb61fdf03c'
down_revision = 'e93ead9de071'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
