"""Autogenerated

Revision ID: 39d234342aa2
Revises: 
Create Date: 2023-03-29 18:36:42.711221

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '39d234342aa2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('publication_name', sa.String(), nullable=False),
    sa.Column('publication_short', sa.String(length=6), nullable=False),
    sa.Column('published_date', sa.DateTime(), nullable=False),
    sa.Column('authors', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', postgresql.ARRAY(sa.String(), dimensions=1), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('articles')
    # ### end Alembic commands ###
