"""Autogenerated

Revision ID: 4290aee0be60
Revises: 39d234342aa2
Create Date: 2023-03-29 18:38:51.675744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4290aee0be60'
down_revision = '39d234342aa2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
