"""Autogenerated

Revision ID: 4f51814514cd
Revises: ef6d01d9bc53
Create Date: 2023-03-29 18:49:29.785185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f51814514cd'
down_revision = 'ef6d01d9bc53'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
