"""Autogenerated

Revision ID: 75c67e9dacdf
Revises: 
Create Date: 2023-03-17 23:07:03.792818

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "75c67e9dacdf"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "articles",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("publication", sa.String(), nullable=True),
        sa.Column("pubdate", sa.DateTime(), nullable=True),
        sa.Column("authors", sa.String(), nullable=True),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("body", postgresql.ARRAY(sa.String(), dimensions=1), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("articles")
    # ### end Alembic commands ###
