"""Autogenerated

Revision ID: 76cddb9c5e40
Revises: 17fb61fdf03c
Create Date: 2023-03-29 18:58:42.945828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76cddb9c5e40'
down_revision = '17fb61fdf03c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
