"""Autogenerated

Revision ID: ef6d01d9bc53
Revises: 4290aee0be60
Create Date: 2023-03-29 18:46:35.605925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef6d01d9bc53'
down_revision = '4290aee0be60'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
