version: '3.3'
services:
  database:
    image: postgres:14-bullseye
    restart: unless-stopped
    user: postgres
    env_file:
      - .env
    ports:
      - "8002:${POSTGRES_PORT}"
    volumes:
      - ./service-database:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 2s
      timeout: 60s
  orm:
    image: service-orm:latest
    volumes:
      - ./service-orm:/usr/src/app
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy
  webdriver:
    restart: unless-stopped
    ports:
      - '8001:4444'
      # uncomment for live browser view
      # - '7900:7900'
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "--silent",
          "--fail",
          "http://localhost:4444"
        ]
      interval: 2s
      timeout: 60s
    image: 'selenium/standalone-firefox:4.8.1-20230306'
    depends_on:
      orm:
        condition: service_completed_successfully
  scraper:
    restart: unless-stopped
    image: service-scraper:latest
    volumes:
      - ./service-scraper:/usr/src/app
    env_file:
      - .env
    depends_on:
      webdriver:
        condition: service_healthy
  web:
    restart: unless-stopped
    image: service-web:latest
    ports:
      - 8000:8000
    volumes:
      - ./service-web:/usr/src/app
    env_file:
      - .env
    depends_on:
      orm:
        condition: service_completed_successfully
