version: '3.3'
services:
    mongodb:
        ports:
            - '27017:27017'
        volumes:
            - ./db:/data/db
        image: mongo:4
        restart: unless-stopped
        environment:
            - TZ=Europe/London
    api:
        build: ./api
        command: python main.py
        volumes:
        - ./api:/usr/src/app
        ports:
        #- 8558:8558
        - 8558:80
        environment:
            - TZ=Europe/London
    scraper:
        build: ./scraper
        command: python main.py
        volumes:
            - ./scraper:/usr/src/app
        environment:
            - TZ=Europe/London
    swag:
        image: lscr.io/linuxserver/swag
        cap_add:
        - NET_ADMIN
        environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/London
        - URL=elgrove.xyz
        - VALIDATION=dns
        - SUBDOMAINS=news #optional
        - DNSPLUGIN=cloudflare #optional
        - EMAIL= aaronlovegrove@protonmail.com
        volumes:
        - ./swag:/config
        ports:
        - 443:443
        - 80:80 #optional
        restart: unless-stopped