version: '3.3'
services:
  browser:
    ports:
      - '4444:4444'
      - '7900:7900'
    image: 'selenium/standalone-firefox:4.8.1-20230306'
  scraper:
    build: ./scraper
    command: python main.py
    volumes:
      - ./scraper:/usr/src/app
    environment:
      - TZ=Europe/London
