[tool.poetry]
name = "scraper"
version = "0.1.0"
description = ""
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.9"
bs4 = "^0.0.1"
selenium = "^4.8.2"
lxml = "^4.9.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
