# renew_before_expiry = 30 days
version = 1.21.0
archive_dir = /etc/letsencrypt/archive/elgrove.xyz
cert = /etc/letsencrypt/live/elgrove.xyz/cert.pem
privkey = /etc/letsencrypt/live/elgrove.xyz/privkey.pem
chain = /etc/letsencrypt/live/elgrove.xyz/chain.pem
fullchain = /etc/letsencrypt/live/elgrove.xyz/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = d1e1573fa7c686346c39c40d669fa9f5
rsa_key_size = 4096
server = https://acme-v02.api.letsencrypt.org/directory
authenticator = dns-cloudflare
dns_cloudflare = True
dns_cloudflare_credentials = /config/dns-conf/cloudflare.ini
