"""Autogenerated

Revision ID: 2b5c20c10315
Revises: c29b6ad4dd15
Create Date: 2023-05-26 22:12:27.850766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b5c20c10315'
down_revision = 'c29b6ad4dd15'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
