"""Autogenerated

Revision ID: 61593d6e9147
Revises: 
Create Date: 2023-05-23 22:11:05.683135

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '61593d6e9147'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('uuid', sa.String(), server_default=sa.text('gen_random_uuid()'), nullable=True),
    sa.Column('publication_name', sa.String(), nullable=False),
    sa.Column('publication_short', sa.String(length=6), nullable=False),
    sa.Column('published_date', sa.DateTime(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('authors', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', postgresql.ARRAY(sa.String(), dimensions=1), nullable=False),
    sa.Column('page_rank', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('publication_name', 'authors', 'title')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('articles')
    # ### end Alembic commands ###
