"""Autogenerated

Revision ID: 7e8d9ec4a7f3
Revises: 2b5c20c10315
Create Date: 2023-05-26 22:15:40.946267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e8d9ec4a7f3'
down_revision = '2b5c20c10315'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
