"""Autogenerated

Revision ID: c29b6ad4dd15
Revises: 4d0aef245b3d
Create Date: 2023-05-26 18:43:03.977167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c29b6ad4dd15'
down_revision = '4d0aef245b3d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
