"""Autogenerated

Revision ID: e8c72d3c2ae0
Revises: 7e8d9ec4a7f3
Create Date: 2023-05-26 22:18:48.504222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8c72d3c2ae0'
down_revision = '7e8d9ec4a7f3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
